# Generated by Django 3.1.5 on 2021-02-09 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210208_1430'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='eu_vi',
            table='core_eu_vi',
        ),
    ]
